offsets = {
            'small_block': (0x00000,0x0CF2B),
            'small_block_backup': ((0x00000 + 0x40000),(0x0CF2B + 0x40000)),
            'small_block_footer': (0x0CF2B - 0x14, 0x0CF2B),
            'big_block': (0x0CF2C, 0x1F10F),
            'big_block_backup': ((0x0CF2C + 0x40000),(0x1F10F + 0x40000)),
            'big_block_footer': (0x1F10F - 0x14, 0x1F10F),
            'trainer_name': (0x68,0x77),
            'trainer_id': (0x78,0x79),
            'secret_id': (0x7A,0x7B),
            'money': (0x7C,0x7F),
            'gender': 0x80,
            'badges': 0x82,
            'in_party': 0x9C,
            'party_blocks': (0xA0,0x627),
            'items_placeholder': (0x00630,0x008C3),
            'keyitems_placeholder': (0x008C4,0x0098B),
            'machines_placeholder': (0x0098C,0x00B4B),
            'medicine_placeholder': (0x00B4C,0x00BEB),
            'berries_placeholder': (0x00BDC,0x00CEB),
            'pokeballs_placeholder': (0x00CEC,0x00D27),
            'battleitems_placeholder': (0x00D28,0x00D5B),
            'mail_placeholder': (0x00D5C,0x00D8B),
            'item': (0x02,0x03),
            'item_amount':(0x02,0x03),
        }
item_assoc = {
    0:'None',
    1:'Master Ball',
    2:'Ultra Ball',
    3:'Great Ball',
    4:'Poke Ball (item)',
    5:'Safari Ball',
    6:'Net Ball',
    7:'Dive Ball',
    8:'Nest Ball',
    9:'Repeat Ball',
    10:'Timer Ball',
    11:'Luxury Ball',
    12:'Premier Ball',
    13:'Dusk Ball',
    14:'Heal Ball',
    15:'Quick Ball',
    16:'Cherish Ball',
    17:'Potion',
    18:'Antidote',
    19:'Burn Heal',
    20:'Ice Heal',
    21:'Awakening',
    22:'Paralyze Heal',
    23:'Full Restore',
    24:'Max Potion',
    25:'Hyper Potion',
    26:'Super Potion',
    27:'Full Heal',
    28:'Revive',
    29:'Max Revive',
    30:'Fresh Water',
    31:'Soda Pop',
    32:'Lemonade',
    33:'Moomoo Milk',
    34:'Energy Powder',
    35:'Energy Root',
    36:'Heal Powder',
    37:'Revival Herb',
    38:'Ether',
    39:'Max Ether',
    40:'Elixir',
    41:'Max Elixir',
    42:'Lava Cookie',
    43:'Berry Juice',
    44:'Sacred Ash',
    45:'HP Up',
    46:'Protein',
    47:'Iron',
    48:'Carbos',
    49:'Calcium',
    50:'Rare Candy',
    51:'PP Up',
    52:'Zinc',
    53:'PP Max',
    54:'Old Gateau',
    55:'Guard Spec.',
    56:'Dire Hit',
    57:'X Attack',
    58:'X Defense',
    59:'X Speed',
    60:'X Accuracy',
    61:'X Sp. Atk',
    62:'X Sp. Def',
    63:'Poke Doll',
    64:'Fluffy Tail',
    65:'Blue Flute',
    66:'Yellow Flute',
    67:'Red Flute',
    68:'Black Flute',
    69:'White Flute',
    70:'Shoal Salt',
    71:'Shoal Shell',
    72:'Red Shard',
    73:'Blue Shard',
    74:'Yellow Shard',
    75:'Green Shard',
    76:'Super Repel',
    77:'Max Repel',
    78:'Escape Rope',
    79:'Repel',
    80:'Sun Stone',
    81:'Moon Stone',
    82:'Fire Stone',
    83:'Thunder Stone',
    84:'Water Stone',
    85:'Leaf Stone',
    86:'Tiny Mushroom',
    87:'Big Mushroom',
    88:'Pearl (item)',
    89:'Big Pearl',
    90:'Stardust',
    91:'Star Piece',
    92:'Nugget',
    93:'Heart Scale',
    94:'Honey',
    95:'Growth Mulch',
    96:'Damp Mulch',
    97:'Stable Mulch',
    98:'Gooey Mulch',
    99:'Root Fossil',
    100:'Claw Fossil',
    101:'Helix Fossil',
    102:'Dome Fossil',
    103:'Old Amber',
    104:'Armor Fossil',
    105:'Skull Fossil',
    106:'Rare Bone',
    107:'Shiny Stone',
    108:'Dusk Stone',
    109:'Dawn Stone',
    110:'Oval Stone',
    111:'Odd Keystone',
    112:'Griseous Orb',
    113:'unknown',
    114:'unknown',
    115:'unknown',
    116:'unknown',
    117:'unknown',
    118:'unknown',
    119:'unknown',
    120:'unknown',
    121:'unknown',
    122:'unknown',
    123:'unknown',
    124:'unknown',
    125:'unknown',
    126:'unknown',
    127:'unknown',
    128:'unknown',
    129:'unknown',
    130:'unknown',
    131:'unknown',
    132:'unknown',
    133:'unknown',
    134:'unknown',
    135:'Adamant Orb',
    136:'Lustrous Orb',
    137:'Grass Mail',
    138:'Flame Mail',
    139:'Bubble Mail',
    140:'Bloom Mail',
    141:'Tunnel Mail',
    142:'Steel Mail',
    143:'Heart Mail',
    144:'Snow Mail',
    145:'Space Mail',
    146:'Air Mail',
    147:'Mosaic Mail',
    148:'Brick Mail',
    149:'Cheri Berry',
    150:'Chesto Berry',
    151:'Pecha Berry',
    152:'Rawst Berry',
    153:'Aspear Berry',
    154:'Leppa Berry',
    155:'Oran Berry',
    156:'Persim Berry',
    157:'Lum Berry',
    158:'Sitrus Berry',
    159:'Figy Berry',
    160:'Wiki Berry',
    161:'Mago Berry',
    162:'Aguav Berry',
    163:'Iapapa Berry',
    164:'Razz Berry',
    165:'Bluk Berry',
    166:'Nanab Berry',
    167:'Wepear Berry',
    168:'Pinap Berry',
    169:'Pomeg Berry',
    170:'Kelpsy Berry',
    171:'Qualot Berry',
    172:'Hondew Berry',
    173:'Grepa Berry',
    174:'Tamato Berry',
    175:'Cornn Berry',
    176:'Magost Berry',
    177:'Rabuta Berry',
    178:'Nomel Berry',
    179:'Spelon Berry',
    180:'Pamtre Berry',
    181:'Watmel Berry',
    182:'Durin Berry',
    183:'Belue Berry',
    184:'Occa Berry',
    185:'Passho Berry',
    186:'Wacan Berry',
    187:'Rindo Berry',
    188:'Yache Berry',
    189:'Chople Berry',
    190:'Kebia Berry',
    191:'Shuca Berry',
    192:'Coba Berry',
    193:'Payapa Berry',
    194:'Tanga Berry',
    195:'Charti Berry',
    196:'Kasib Berry',
    197:'Haban Berry',
    198:'Colbur Berry',
    199:'Babiri Berry',
    200:'Chilan Berry',
    201:'Liechi Berry',
    202:'Ganlon Berry',
    203:'Salac Berry',
    204:'Petaya Berry',
    205:'Apicot Berry',
    206:'Lansat Berry',
    207:'Starf Berry',
    208:'Enigma Berry',
    209:'Micle Berry',
    210:'Custap Berry',
    211:'Jaboca Berry',
    212:'Rowap Berry',
    213:'Bright Powder',
    214:'White Herb',
    215:'Macho Brace',
    216:'Exp. Share',
    217:'Quick Claw',
    218:'Soothe Bell',
    219:'Mental Herb',
    220:'Choice Band',
    221:'Kings Rock',
    222:'Silver Powder',
    223:'Amulet Coin',
    224:'Cleanse Tag',
    225:'Soul Dew',
    226:'Deep Sea Tooth',
    227:'Deep Sea Scale',
    228:'Smoke Ball',
    229:'Everstone',
    230:'Focus Band',
    231:'Lucky Egg',
    232:'Scope Lens',
    233:'Metal Coat',
    234:'Leftovers',
    235:'Dragon Scale',
    236:'Light Ball',
    237:'Soft Sand',
    238:'Hard Stone',
    239:'Miracle Seed',
    240:'Black Glasses',
    241:'Black Belt (item)',
    242:'Magnet',
    243:'Mystic Water',
    244:'Sharp Beak',
    245:'Poison Barb',
    246:'Never-Melt Ice',
    247:'Spell Tag',
    248:'Twisted Spoon',
    249:'Charcoal',
    250:'Dragon Fang',
    251:'Silk Scarf',
    252:'Upgrade',
    253:'Shell Bell',
    254:'Sea Incense',
    255:'Lax Incense',
    256:'Lucky Punch',
    257:'Metal Powder',
    258:'Thick Club',
    259:'Leek',
    260:'Red Scarf',
    261:'Blue Scarf',
    262:'Pink Scarf',
    263:'Green Scarf',
    264:'Yellow Scarf',
    265:'Wide Lens',
    266:'Muscle Band',
    267:'Wise Glasses',
    268:'Expert Belt',
    269:'Light Clay',
    270:'Life Orb',
    271:'Power Herb',
    272:'Toxic Orb',
    273:'Flame Orb',
    274:'Quick Powder',
    275:'Focus Sash',
    276:'Zoom Lens',
    277:'Metronome (item)',
    278:'Iron Ball',
    279:'Lagging Tail',
    280:'Destiny Knot',
    281:'Black Sludge',
    282:'Icy Rock',
    283:'Smooth Rock',
    284:'Heat Rock',
    285:'Damp Rock',
    286:'Grip Claw',
    287:'Choice Scarf',
    288:'Sticky Barb',
    289:'Power Bracer',
    290:'Power Belt',
    291:'Power Lens',
    292:'Power Band',
    293:'Power Anklet',
    294:'Power Weight',
    295:'Shed Shell',
    296:'Big Root',
    297:'Choice Specs',
    298:'Flame Plate',
    299:'Splash Plate',
    300:'Zap Plate',
    301:'Meadow Plate',
    302:'Icicle Plate',
    303:'Fist Plate',
    304:'Toxic Plate',
    305:'Earth Plate',
    306:'Sky Plate',
    307:'Mind Plate',
    308:'Insect Plate',
    309:'Stone Plate',
    310:'Spooky Plate',
    311:'Draco Plate',
    312:'Dread Plate',
    313:'Iron Plate',
    314:'Odd Incense',
    315:'Rock Incense',
    316:'Full Incense',
    317:'Wave Incense',
    318:'Rose Incense',
    319:'Luck Incense',
    320:'Pure Incense',
    321:'Protector',
    322:'Electirizer',
    323:'Magmarizer',
    324:'Dubious Disc',
    325:'Reaper Cloth',
    326:'Razor Claw',
    327:'Razor Fang',
    328:'TM01',
    329:'TM02',
    330:'TM03',
    331:'TM04',
    332:'TM05',
    333:'TM06',
    334:'TM07',
    335:'TM08',
    336:'TM09',
    337:'TM10',
    338:'TM11',
    339:'TM12',
    340:'TM13',
    341:'TM14',
    342:'TM15',
    343:'TM16',
    344:'TM17',
    345:'TM18',
    346:'TM19',
    347:'TM20',
    348:'TM21',
    349:'TM22',
    350:'TM23',
    351:'TM24',
    352:'TM25',
    353:'TM26',
    354:'TM27',
    355:'TM28',
    356:'TM29',
    357:'TM30',
    358:'TM31',
    359:'TM32',
    360:'TM33',
    361:'TM34',
    362:'TM35',
    363:'TM36',
    364:'TM37',
    365:'TM38',
    366:'TM39',
    367:'TM40',
    368:'TM41',
    369:'TM42',
    370:'TM43',
    371:'TM44',
    372:'TM45',
    373:'TM46',
    374:'TM47',
    375:'TM48',
    376:'TM49',
    377:'TM50',
    378:'TM51',
    379:'TM52',
    380:'TM53',
    381:'TM54',
    382:'TM55',
    383:'TM56',
    384:'TM57',
    385:'TM58',
    386:'TM59',
    387:'TM60',
    388:'TM61',
    389:'TM62',
    390:'TM63',
    391:'TM64',
    392:'TM65',
    393:'TM66',
    394:'TM67',
    395:'TM68',
    396:'TM69',
    397:'TM70',
    398:'TM71',
    399:'TM72',
    400:'TM73',
    401:'TM74',
    402:'TM75',
    403:'TM76',
    404:'TM77',
    405:'TM78',
    406:'TM79',
    407:'TM80',
    408:'TM81',
    409:'TM82',
    410:'TM83',
    411:'TM84',
    412:'TM85',
    413:'TM86',
    414:'TM87',
    415:'TM88',
    416:'TM89',
    417:'TM90',
    418:'TM91',
    419:'TM92',
    420:'HM01',
    421:'HM02',
    422:'HM03',
    423:'HM04',
    424:'HM05',
    425:'HM06',
    426:'HM07',
    427:'HM08',
    428:'Explorer Kit',
    429:'Loot Sack',
    430:'Rule Book',
    431:'Poke Radar',
    432:'Point Card',
    433:'Journal',
    434:'Seal Case',
    435:'Fashion Case',
    436:'Seal Bag',
    437:'Pal Pad',
    438:'Works Key',
    439:'Old Charm',
    440:'Galactic Key',
    441:'Red Chain',
    442:'Town Map',
    443:'Vs. Seeker',
    444:'Coin Case',
    445:'Old Rod',
    446:'Good Rod',
    447:'Super Rod',
    448:'Sprayduck',
    449:'Poffin Case',
    450:'Bicycle',
    451:'Suite Key',
    452:'Oaks Letter',
    453:'Lunar Wing',
    454:'Member Card',
    455:'Azure Flute',
    456:'S.S. Ticket',
    457:'Contest Pass',
    458:'Magma Stone',
    459:'Parcel',
    460:'Coupon 1',
    461:'Coupon 2',
    462:'Coupon 3',
    463:'Storage Key (Sinnoh)',
    464:'Secret Potion',
    465:'Vs. Recorder',
    466:'Gracidea',
    467:'Secret Key (Sinnoh)',
    468:'Apricorn Box',
    469:'Unown Report',
    470:'Berry Pots',
    471:'Dowsing Machine',
    472:'Blue Card',
    473:'Slowpoke Tail',
    474:'Clear Bell',
    475:'Card Key (Johto)',
    476:'Basement Key (Johto)',
    477:'Squirt Bottle',
    478:'Red Scale',
    479:'Lost Item',
    480:'Pass',
    481:'Machine Part',
    482:'Silver Wing',
    483:'Rainbow Wing',
    484:'Mystery Egg',
    485:'Red Apricorn',
    486:'Yellow Apricorn',
    487:'Blue Apricorn',
    488:'Green Apricorn',
    489:'Pink Apricorn',
    490:'White Apricorn',
    491:'Black Apricorn',
    492:'Fast Ball',
    493:'Level Ball',
    494:'Lure Ball',
    495:'Heavy Ball',
    496:'Love Ball',
    497:'Friend Ball',
    498:'Moon Ball',
    499:'Sport Ball',
    500:'Park Ball',
    501:'Photo Album',
    502:'GB Sounds',
    503:'Tidal Bell',
    504:'Rage Candy Bar',
    505:'Data Card 01',
    506:'Data Card 02',
    507:'Data Card 03',
    508:'Data Card 04',
    509:'Data Card 05',
    510:'Data Card 06',
    511:'Data Card 07',
    512:'Data Card 08',
    513:'Data Card 09',
    514:'Data Card 10',
    515:'Data Card 11',
    516:'Data Card 12',
    517:'Data Card 13',
    518:'Data Card 14',
    519:'Data Card 15',
    520:'Data Card 16',
    521:'Data Card 17',
    522:'Data Card 18',
    523:'Data Card 19',
    524:'Data Card 20',
    525:'Data Card 21',
    526:'Data Card 22',
    527:'Data Card 23',
    528:'Data Card 24',
    529:'Data Card 25',
    530:'Data Card 26',
    531:'Data Card 27',
    532:'Jade Orb',
    533:'Lock Capsule',
    534:'Red Orb',
    535:'Blue Orb',
    536:'Enigma Stone',
}
shifts = {
                0:('ABCD','ABCD'),
                1:('ABDC','ABDC'),
                2:('ACBD','ACBD'),
                3:('ACDB','ADBC'),
                4:('ADBC','ACDB'),
                5:('ADCB','ADCB'),
                6:('BACD','BACD'),
                7:('BADC','BADC'),
                8:('BCAD','CABD'),
                9:('BCDA','DABC'),
                10:('BDAC','CADB'),
                11:('BDCA','DACB'),
                12:('CABD','BCAD'),
                13:('CADB','BDAC'),
                14:('CBAD','CBAD'),
                15:('CBDA','DBAC'),
                16:('CDAB','CDAB'),
                17:('CDBA','DCAB'),
                18:('DABC','BCDA'),
                19:('DACB','BDCA'),
                20:('DBAC','CBDA'),
                21:('DBCA','DBCA'),
                22:('DCAB','CDBA'),
                23:('DCBA','DCBA'),
                }
pkmn_indexes = {
    0:'-----',
    1:'Bulbasaur',
    2:'Ivysaur',
    3:'Venusaur',
    4:'Charmander',
    5:'Charmeleon',
    6:'Charizard',
    7:'Squirtle',
    8:'Wartortle',
    9:'Blastoise',
    10:'Caterpie',
    11:'Metapod',
    12:'Butterfree',
    13:'Weedle',
    14:'Kakuna',
    15:'Beedrill',
    16:'Pidgey',
    17:'Pidgeotto',
    18:'Pidgeot',
    19:'Rattata',
    20:'Raticate',
    21:'Spearow',
    22:'Fearow',
    23:'Ekans',
    24:'Arbok',
    25:'Pikachu',
    26:'Raichu',
    27:'Sandshrew',
    28:'Sandslash',
    29:'Nidoran♀',
    30:'Nidorina',
    31:'Nidoqueen',
    32:'Nidoran♂',
    33:'Nidorino',
    34:'Nidoking',
    35:'Clefairy',
    36:'Clefable',
    37:'Vulpix',
    38:'Ninetales',
    39:'Jigglypuff',
    40:'Wigglytuff',
    41:'Zubat',
    42:'Golbat',
    43:'Oddish',
    44:'Gloom',
    45:'Vileplume',
    46:'Paras',
    47:'Parasect',
    48:'Venonat',
    49:'Venomoth',
    50:'Diglett',
    51:'Dugtrio',
    52:'Meowth',
    53:'Persian',
    54:'Psyduck',
    55:'Golduck',
    56:'Mankey',
    57:'Primeape',
    58:'Growlithe',
    59:'Arcanine',
    60:'Poliwag',
    61:'Poliwhirl',
    62:'Poliwrath',
    63:'Abra',
    64:'Kadabra',
    65:'Alakazam',
    66:'Machop',
    67:'Machoke',
    68:'Machamp',
    69:'Bellsprout',
    70:'Weepinbell',
    71:'Victreebel',
    72:'Tentacool',
    73:'Tentacruel',
    74:'Geodude',
    75:'Graveler',
    76:'Golem',
    77:'Ponyta',
    78:'Rapidash',
    79:'Slowpoke',
    80:'Slowbro',
    81:'Magnemite',
    82:'Magneton',
    83:'Farfetchd',
    84:'Doduo',
    85:'Dodrio',
    86:'Seel',
    87:'Dewgong',
    88:'Grimer',
    89:'Muk',
    90:'Shellder',
    91:'Cloyster',
    92:'Gastly',
    93:'Haunter',
    94:'Gengar',
    95:'Onix',
    96:'Drowzee',
    97:'Hypno',
    98:'Krabby',
    99:'Kingler',
    100:'Voltorb',
    101:'Electrode',
    102:'Exeggcute',
    103:'Exeggutor',
    104:'Cubone',
    105:'Marowak',
    106:'Hitmonlee',
    107:'Hitmonchan',
    108:'Lickitung',
    109:'Koffing',
    110:'Weezing',
    111:'Rhyhorn',
    112:'Rhydon',
    113:'Chansey',
    114:'Tangela',
    115:'Kangaskhan',
    116:'Horsea',
    117:'Seadra',
    118:'Goldeen',
    119:'Seaking',
    120:'Staryu',
    121:'Starmie',
    122:'Mr. Mime',
    123:'Scyther',
    124:'Jynx',
    125:'Electabuzz',
    126:'Magmar',
    127:'Pinsir',
    128:'Tauros',
    129:'Magikarp',
    130:'Gyarados',
    131:'Lapras',
    132:'Ditto',
    133:'Eevee',
    134:'Vaporeon',
    135:'Jolteon',
    136:'Flareon',
    137:'Porygon',
    138:'Omanyte',
    139:'Omastar',
    140:'Kabuto',
    141:'Kabutops',
    142:'Aerodactyl',
    143:'Snorlax',
    144:'Articuno',
    145:'Zapdos',
    146:'Moltres',
    147:'Dratini',
    148:'Dragonair',
    149:'Dragonite',
    150:'Mewtwo',
    151:'Mew',
    152:'Chikorita',
    153:'Bayleef',
    154:'Meganium',
    155:'Cyndaquil',
    156:'Quilava',
    157:'Typhlosion',
    158:'Totodile',
    159:'Croconaw',
    160:'Feraligatr',
    161:'Sentret',
    162:'Furret',
    163:'Hoothoot',
    164:'Noctowl',
    165:'Ledyba',
    166:'Ledian',
    167:'Spinarak',
    168:'Ariados',
    169:'Crobat',
    170:'Chinchou',
    171:'Lanturn',
    172:'Pichu',
    173:'Cleffa',
    174:'Igglybuff',
    175:'Togepi',
    176:'Togetic',
    177:'Natu',
    178:'Xatu',
    179:'Mareep',
    180:'Flaaffy',
    181:'Ampharos',
    182:'Bellossom',
    183:'Marill',
    184:'Azumarill',
    185:'Sudowoodo',
    186:'Politoed',
    187:'Hoppip',
    188:'Skiploom',
    189:'Jumpluff',
    190:'Aipom',
    191:'Sunkern',
    192:'Sunflora',
    193:'Yanma',
    194:'Wooper',
    195:'Quagsire',
    196:'Espeon',
    197:'Umbreon',
    198:'Murkrow',
    199:'Slowking',
    200:'Misdreavus',
    201:'Unown',
    202:'Wobbuffet',
    203:'Girafarig',
    204:'Pineco',
    205:'Forretress',
    206:'Dunsparce',
    207:'Gligar',
    208:'Steelix',
    209:'Snubbull',
    210:'Granbull',
    211:'Qwilfish',
    212:'Scizor',
    213:'Shuckle',
    214:'Heracross',
    215:'Sneasel',
    216:'Teddiursa',
    217:'Ursaring',
    218:'Slugma',
    219:'Magcargo',
    220:'Swinub',
    221:'Piloswine',
    222:'Corsola',
    223:'Remoraid',
    224:'Octillery',
    225:'Delibird',
    226:'Mantine',
    227:'Skarmory',
    228:'Houndour',
    229:'Houndoom',
    230:'Kingdra',
    231:'Phanpy',
    232:'Donphan',
    233:'Porygon2',
    234:'Stantler',
    235:'Smeargle',
    236:'Tyrogue',
    237:'Hitmontop',
    238:'Smoochum',
    239:'Elekid',
    240:'Magby',
    241:'Miltank',
    242:'Blissey',
    243:'Raikou',
    244:'Entei',
    245:'Suicune',
    246:'Larvitar',
    247:'Pupitar',
    248:'Tyranitar',
    249:'Lugia',
    250:'Ho-Oh',
    251:'Celebi',
    252:'Treecko',
    253:'Grovyle',
    254:'Sceptile',
    255:'Torchic',
    256:'Combusken',
    257:'Blaziken',
    258:'Mudkip',
    259:'Marshtomp',
    260:'Swampert',
    261:'Poochyena',
    262:'Mightyena',
    263:'Zigzagoon',
    264:'Linoone',
    265:'Wurmple',
    266:'Silcoon',
    267:'Beautifly',
    268:'Cascoon',
    269:'Dustox',
    270:'Lotad',
    271:'Lombre',
    272:'Ludicolo',
    273:'Seedot',
    274:'Nuzleaf',
    275:'Shiftry',
    276:'Taillow',
    277:'Swellow',
    278:'Wingull',
    279:'Pelipper',
    280:'Ralts',
    281:'Kirlia',
    282:'Gardevoir',
    283:'Surskit',
    284:'Masquerain',
    285:'Shroomish',
    286:'Breloom',
    287:'Slakoth',
    288:'Vigoroth',
    289:'Slaking',
    290:'Nincada',
    291:'Ninjask',
    292:'Shedinja',
    293:'Whismur',
    294:'Loudred',
    295:'Exploud',
    296:'Makuhita',
    297:'Hariyama',
    298:'Azurill',
    299:'Nosepass',
    300:'Skitty',
    301:'Delcatty',
    302:'Sableye',
    303:'Mawile',
    304:'Aron',
    305:'Lairon',
    306:'Aggron',
    307:'Meditite',
    308:'Medicham',
    309:'Electrike',
    310:'Manectric',
    311:'Plusle',
    312:'Minun',
    313:'Volbeat',
    314:'Illumise',
    315:'Roselia',
    316:'Gulpin',
    317:'Swalot',
    318:'Carvanha',
    319:'Sharpedo',
    320:'Wailmer',
    321:'Wailord',
    322:'Numel',
    323:'Camerupt',
    324:'Torkoal',
    325:'Spoink',
    326:'Grumpig',
    327:'Spinda',
    328:'Trapinch',
    329:'Vibrava',
    330:'Flygon',
    331:'Cacnea',
    332:'Cacturne',
    333:'Swablu',
    334:'Altaria',
    335:'Zangoose',
    336:'Seviper',
    337:'Lunatone',
    338:'Solrock',
    339:'Barboach',
    340:'Whiscash',
    341:'Corphish',
    342:'Crawdaunt',
    343:'Baltoy',
    344:'Claydol',
    345:'Lileep',
    346:'Cradily',
    347:'Anorith',
    348:'Armaldo',
    349:'Feebas',
    350:'Milotic',
    351:'Castform',
    352:'Kecleon',
    353:'Shuppet',
    354:'Banette',
    355:'Duskull',
    356:'Dusclops',
    357:'Tropius',
    358:'Chimecho',
    359:'Absol',
    360:'Wynaut',
    361:'Snorunt',
    362:'Glalie',
    363:'Spheal',
    364:'Sealeo',
    365:'Walrein',
    366:'Clamperl',
    367:'Huntail',
    368:'Gorebyss',
    369:'Relicanth',
    370:'Luvdisc',
    371:'Bagon',
    372:'Shelgon',
    373:'Salamence',
    374:'Beldum',
    375:'Metang',
    376:'Metagross',
    377:'Regirock',
    378:'Regice',
    379:'Registeel',
    380:'Latias',
    381:'Latios',
    382:'Kyogre',
    383:'Groudon',
    384:'Rayquaza',
    385:'Jirachi',
    386:'Deoxys',
    387:'Turtwig',
    388:'Grotle',
    389:'Torterra',
    390:'Chimchar',
    391:'Monferno',
    392:'Infernape',
    393:'Piplup',
    394:'Prinplup',
    395:'Empoleon',
    396:'Starly',
    397:'Staravia',
    398:'Staraptor',
    399:'Bidoof',
    400:'Bibarel',
    401:'Kricketot',
    402:'Kricketune',
    403:'Shinx',
    404:'Luxio',
    405:'Luxray',
    406:'Budew',
    407:'Roserade',
    408:'Cranidos',
    409:'Rampardos',
    410:'Shieldon',
    411:'Bastiodon',
    412:'Burmy',
    413:'Wormadam',
    414:'Mothim',
    415:'Combee',
    416:'Vespiquen',
    417:'Pachirisu',
    418:'Buizel',
    419:'Floatzel',
    420:'Cherubi',
    421:'Cherrim',
    422:'Shellos',
    423:'Gastrodon',
    424:'Ambipom',
    425:'Drifloon',
    426:'Drifblim',
    427:'Buneary',
    428:'Lopunny',
    429:'Mismagius',
    430:'Honchkrow',
    431:'Glameow',
    432:'Purugly',
    433:'Chingling',
    434:'Stunky',
    435:'Skuntank',
    436:'Bronzor',
    437:'Bronzong',
    438:'Bonsly',
    439:'Mime Jr.',
    440:'Happiny',
    441:'Chatot',
    442:'Spiritomb',
    443:'Gible',
    444:'Gabite',
    445:'Garchomp',
    446:'Munchlax',
    447:'Riolu',
    448:'Lucario',
    449:'Hippopotas',
    450:'Hippowdon',
    451:'Skorupi',
    452:'Drapion',
    453:'Croagunk',
    454:'Toxicroak',
    455:'Carnivine',
    456:'Finneon',
    457:'Lumineon',
    458:'Mantyke',
    459:'Snover',
    460:'Abomasnow',
    461:'Weavile',
    462:'Magnezone',
    463:'Lickilicky',
    464:'Rhyperior',
    465:'Tangrowth',
    466:'Electivire',
    467:'Magmortar',
    468:'Togekiss',
    469:'Yanmega',
    470:'Leafeon',
    471:'Glaceon',
    472:'Gliscor',
    473:'Mamoswine',
    474:'Porygon-Z',
    475:'Gallade',
    476:'Probopass',
    477:'Dusknoir',
    478:'Froslass',
    479:'Rotom',
    480:'Uxie',
    481:'Mesprit',
    482:'Azelf',
    483:'Dialga',
    484:'Palkia',
    485:'Heatran',
    486:'Regigigas',
    487:'Giratina',
    488:'Cresselia',
    489:'Phione',
    490:'Manaphy',
    491:'Darkrai',
    492:'Shaymin',
    493:'Arceus',
    494:'Pokémon Egg',
    495:'Manaphy Egg',
    496:'Deoxys',
    497:'Deoxys',
    498:'Deoxys',
    499:'Wormadam',
    500:'Wormadam',
    501:'Giratina',
    502:'Shaymin',
    503:'Rotom',
    504:'Rotom',
    505:'Rotom',
    506:'Rotom',
    507:'Rotom',
}
pkmn_types = {
    '-----':'Normal',
    'Bulbasaur':('Grass', 'Poison'),
    'Ivysaur':('Grass', 'Poison'),
    'Venusaur':('Grass', 'Poison'),
    'Charmander':'Fire',
    'Charmeleon':'Fire',
    'Charizard':('Fire', 'Flying'),
    'Squirtle':'Water',
    'Wartortle':'Water',
    'Blastoise':'Water',
    'Caterpie':'Bug',
    'Metapod':'Bug',
    'Butterfree':('Bug', 'Flying'),
    'Weedle':('Bug', 'Poison'),
    'Kakuna':('Bug', 'Poison'),
    'Beedrill':('Bug', 'Poison'),
    'Pidgey':('Normal', 'Flying'),
    'Pidgeotto':('Normal', 'Flying'),
    'Pidgeot':('Normal', 'Flying'),
    'Rattata':'Normal',
    'Raticate':'Normal',
    'Spearow':('Normal', 'Flying'),
    'Fearow':('Normal', 'Flying'),
    'Ekans':'Poison',
    'Arbok':'Poison',
    'Pikachu':'Electric',
    'Raichu':'Electric',
    'Sandshrew':'Ground',
    'Sandslash':'Ground',
    'Nidoran♀':'Poison',
    'Nidorina':'Poison',
    'Nidoqueen':('Poison', 'Ground'),
    'Nidoran♂':'Poison',
    'Nidorino':'Poison',
    'Nidoking':('Poison', 'Ground'),
    'Clefairy':'Normal',
    'Clefable':'Normal',
    'Vulpix':'Fire',
    'Ninetales':'Fire',
    'Jigglypuff':'Normal',
    'Wigglytuff':'Normal',
    'Zubat':('Poison', 'Flying'),
    'Golbat':('Poison', 'Flying'),
    'Oddish':('Grass', 'Poison'),
    'Gloom':('Grass', 'Poison'),
    'Vileplume':('Grass', 'Poison'),
    'Paras':('Bug', 'Grass'),
    'Parasect':('Bug', 'Grass'),
    'Venonat':('Bug', 'Poison'),
    'Venomoth':('Bug', 'Poison'),
    'Diglett':'Ground',
    'Dugtrio':'Ground',
    'Meowth':'Normal',
    'Persian':'Normal',
    'Psyduck':'Water',
    'Golduck':'Water',
    'Mankey':'Fighting',
    'Primeape':'Fighting',
    'Growlithe':'Fire',
    'Arcanine':'Fire',
    'Poliwag':'Water',
    'Poliwhirl':'Water',
    'Poliwrath':('Water', 'Fighting'),
    'Abra':'Psychic',
    'Kadabra':'Psychic',
    'Alakazam':'Psychic',
    'Machop':'Fighting',
    'Machoke':'Fighting',
    'Machamp':'Fighting',
    'Bellsprout':('Grass', 'Poison'),
    'Weepinbell':('Grass', 'Poison'),
    'Victreebel':('Grass', 'Poison'),
    'Tentacool':('Water', 'Poison'),
    'Tentacruel':('Water', 'Poison'),
    'Geodude':('Rock', 'Ground'),
    'Graveler':('Rock', 'Ground'),
    'Golem':('Rock', 'Ground'),
    'Ponyta':'Fire',
    'Rapidash':'Fire',
    'Slowpoke':('Water', 'Psychic'),
    'Slowbro':('Water', 'Psychic'),
    'Magnemite':('Electric', 'Steel'),
    'Magneton':('Electric', 'Steel'),
    'Farfetchd':('Normal', 'Flying'),
    'Doduo':('Normal', 'Flying'),
    'Dodrio':('Normal', 'Flying'),
    'Seel':'Water',
    'Dewgong':('Water', 'Ice'),
    'Grimer':'Poison',
    'Muk':'Poison',
    'Shellder':'Water',
    'Cloyster':('Water', 'Ice'),
    'Gastly':('Ghost', 'Poison'),
    'Haunter':('Ghost', 'Poison'),
    'Gengar':('Ghost', 'Poison'),
    'Onix':('Rock', 'Ground'),
    'Drowzee':'Psychic',
    'Hypno':'Psychic',
    'Krabby':'Water',
    'Kingler':'Water',
    'Voltorb':'Electric',
    'Electrode':'Electric',
    'Exeggcute':('Grass', 'Psychic'),
    'Exeggutor':('Grass', 'Psychic'),
    'Cubone':'Ground',
    'Marowak':'Ground',
    'Hitmonlee':'Fighting',
    'Hitmonchan':'Fighting',
    'Lickitung':'Normal',
    'Koffing':'Poison',
    'Weezing':'Poison',
    'Rhyhorn':('Ground', 'Rock'),
    'Rhydon':('Ground', 'Rock'),
    'Chansey':'Normal',
    'Tangela':'Grass',
    'Kangaskhan':'Normal',
    'Horsea':'Water',
    'Seadra':'Water',
    'Goldeen':'Water',
    'Seaking':'Water',
    'Staryu':'Water',
    'Starmie':('Water', 'Psychic'),
    'Mr. Mime':'Psychic',
    'Scyther':('Bug', 'Flying'),
    'Jynx':('Ice', 'Psychic'),
    'Electabuzz':'Electric',
    'Magmar':'Fire',
    'Pinsir':'Bug',
    'Tauros':'Normal',
    'Magikarp':'Water',
    'Gyarados':('Water', 'Flying'),
    'Lapras':('Water', 'Ice'),
    'Ditto':'Normal',
    'Eevee':'Normal',
    'Vaporeon':'Water',
    'Jolteon':'Electric',
    'Flareon':'Fire',
    'Porygon':'Normal',
    'Omanyte':('Rock', 'Water'),
    'Omastar':('Rock', 'Water'),
    'Kabuto':('Rock', 'Water'),
    'Kabutops':('Rock', 'Water'),
    'Aerodactyl':('Rock', 'Flying'),
    'Snorlax':'Normal',
    'Articuno':('Ice', 'Flying'),
    'Zapdos':('Electric', 'Flying'),
    'Moltres':('Fire', 'Flying'),
    'Dratini':'Dragon',
    'Dragonair':'Dragon',
    'Dragonite':('Dragon', 'Flying'),
    'Mewtwo':'Psychic',
    'Mew':'Psychic',
    'Chikorita':'Grass',
    'Bayleef':'Grass',
    'Meganium':'Grass',
    'Cyndaquil':'Fire',
    'Quilava':'Fire',
    'Typhlosion':'Fire',
    'Totodile':'Water',
    'Croconaw':'Water',
    'Feraligatr':'Water',
    'Sentret':'Normal',
    'Furret':'Normal',
    'Hoothoot':('Normal', 'Flying'),
    'Noctowl':('Normal', 'Flying'),
    'Ledyba':('Bug', 'Flying'),
    'Ledian':('Bug', 'Flying'),
    'Spinarak':('Bug', 'Poison'),
    'Ariados':('Bug', 'Poison'),
    'Crobat':('Poison', 'Flying'),
    'Chinchou':('Water', 'Electric'),
    'Lanturn':('Water', 'Electric'),
    'Pichu':'Electric',
    'Cleffa':'Normal',
    'Igglybuff':'Normal',
    'Togepi':'Normal',
    'Togetic':('Normal', 'Flying'),
    'Natu':('Psychic', 'Flying'),
    'Xatu':('Psychic', 'Flying'),
    'Mareep':'Electric',
    'Flaaffy':'Electric',
    'Ampharos':'Electric',
    'Bellossom':'Grass',
    'Marill':'Water',
    'Azumarill':'Water',
    'Sudowoodo':'Rock',
    'Politoed':'Water',
    'Hoppip':('Grass', 'Flying'),
    'Skiploom':('Grass', 'Flying'),
    'Jumpluff':('Grass', 'Flying'),
    'Aipom':'Normal',
    'Sunkern':'Grass',
    'Sunflora':'Grass',
    'Yanma':('Bug', 'Flying'),
    'Wooper':('Water', 'Ground'),
    'Quagsire':('Water', 'Ground'),
    'Espeon':'Psychic',
    'Umbreon':'Dark',
    'Murkrow':('Dark', 'Flying'),
    'Slowking':('Water', 'Psychic'),
    'Misdreavus':'Ghost',
    'Unown':'Psychic',
    'Wobbuffet':'Psychic',
    'Girafarig':('Normal', 'Psychic'),
    'Pineco':'Bug',
    'Forretress':('Bug', 'Steel'),
    'Dunsparce':'Normal',
    'Gligar':('Ground', 'Flying'),
    'Steelix':('Steel', 'Ground'),
    'Snubbull':'Normal',
    'Granbull':'Normal',
    'Qwilfish':('Water', 'Poison'),
    'Scizor':('Bug', 'Steel'),
    'Shuckle':('Bug', 'Rock'),
    'Heracross':('Bug', 'Fighting'),
    'Sneasel':('Dark', 'Ice'),
    'Teddiursa':'Normal',
    'Ursaring':'Normal',
    'Slugma':'Fire',
    'Magcargo':('Fire', 'Rock'),
    'Swinub':('Ice', 'Ground'),
    'Piloswine':('Ice', 'Ground'),
    'Corsola':('Water', 'Rock'),
    'Remoraid':'Water',
    'Octillery':'Water',
    'Delibird':('Ice', 'Flying'),
    'Mantine':('Water', 'Flying'),
    'Skarmory':('Steel', 'Flying'),
    'Houndour':('Dark', 'Fire'),
    'Houndoom':('Dark', 'Fire'),
    'Kingdra':('Water', 'Dragon'),
    'Phanpy':'Ground',
    'Donphan':'Ground',
    'Porygon2':'Normal',
    'Stantler':'Normal',
    'Smeargle':'Normal',
    'Tyrogue':'Fighting',
    'Hitmontop':'Fighting',
    'Smoochum':('Ice', 'Psychic'),
    'Elekid':'Electric',
    'Magby':'Fire',
    'Miltank':'Normal',
    'Blissey':'Normal',
    'Raikou':'Electric',
    'Entei':'Fire',
    'Suicune':'Water',
    'Larvitar':('Rock', 'Ground'),
    'Pupitar':('Rock', 'Ground'),
    'Tyranitar':('Rock', 'Dark'),
    'Lugia':('Psychic', 'Flying'),
    'Ho-Oh':('Fire', 'Flying'),
    'Celebi':('Psychic', 'Grass'),
    'Treecko':'Grass',
    'Grovyle':'Grass',
    'Sceptile':'Grass',
    'Torchic':'Fire',
    'Combusken':('Fire', 'Fighting'),
    'Blaziken':('Fire', 'Fighting'),
    'Mudkip':'Water',
    'Marshtomp':('Water', 'Ground'),
    'Swampert':('Water', 'Ground'),
    'Poochyena':'Dark',
    'Mightyena':'Dark',
    'Zigzagoon':'Normal',
    'Linoone':'Normal',
    'Wurmple':'Bug',
    'Silcoon':'Bug',
    'Beautifly':('Bug', 'Flying'),
    'Cascoon':'Bug',
    'Dustox':('Bug', 'Poison'),
    'Lotad':('Water', 'Grass'),
    'Lombre':('Water', 'Grass'),
    'Ludicolo':('Water', 'Grass'),
    'Seedot':'Grass',
    'Nuzleaf':('Grass', 'Dark'),
    'Shiftry':('Grass', 'Dark'),
    'Taillow':('Normal', 'Flying'),
    'Swellow':('Normal', 'Flying'),
    'Wingull':('Water', 'Flying'),
    'Pelipper':('Water', 'Flying'),
    'Ralts':'Psychic',
    'Kirlia':'Psychic',
    'Gardevoir':'Psychic',
    'Surskit':('Bug', 'Water'),
    'Masquerain':('Bug', 'Flying'),
    'Shroomish':'Grass',
    'Breloom':('Grass', 'Fighting'),
    'Slakoth':'Normal',
    'Vigoroth':'Normal',
    'Slaking':'Normal',
    'Nincada':('Bug', 'Ground'),
    'Ninjask':('Bug', 'Flying'),
    'Shedinja':('Bug', 'Ghost'),
    'Whismur':'Normal',
    'Loudred':'Normal',
    'Exploud':'Normal',
    'Makuhita':'Fighting',
    'Hariyama':'Fighting',
    'Azurill':'Normal',
    'Nosepass':'Rock',
    'Skitty':'Normal',
    'Delcatty':'Normal',
    'Sableye':('Dark', 'Ghost'),
    'Mawile':'Steel',
    'Aron':('Steel', 'Rock'),
    'Lairon':('Steel', 'Rock'),
    'Aggron':('Steel', 'Rock'),
    'Meditite':('Fighting', 'Psychic'),
    'Medicham':('Fighting', 'Psychic'),
    'Electrike':'Electric',
    'Manectric':'Electric',
    'Plusle':'Electric',
    'Minun':'Electric',
    'Volbeat':'Bug',
    'Illumise':'Bug',
    'Roselia':('Grass', 'Poison'),
    'Gulpin':'Poison',
    'Swalot':'Poison',
    'Carvanha':('Water', 'Dark'),
    'Sharpedo':('Water', 'Dark'),
    'Wailmer':'Water',
    'Wailord':'Water',
    'Numel':('Fire', 'Ground'),
    'Camerupt':('Fire', 'Ground'),
    'Torkoal':'Fire',
    'Spoink':'Psychic',
    'Grumpig':'Psychic',
    'Spinda':'Normal',
    'Trapinch':'Ground',
    'Vibrava':('Ground', 'Dragon'),
    'Flygon':('Ground', 'Dragon'),
    'Cacnea':'Grass',
    'Cacturne':('Grass', 'Dark'),
    'Swablu':('Normal', 'Flying'),
    'Altaria':('Dragon', 'Flying'),
    'Zangoose':'Normal',
    'Seviper':'Poison',
    'Lunatone':('Rock', 'Psychic'),
    'Solrock':('Rock', 'Psychic'),
    'Barboach':('Water', 'Ground'),
    'Whiscash':('Water', 'Ground'),
    'Corphish':'Water',
    'Crawdaunt':('Water', 'Dark'),
    'Baltoy':('Ground', 'Psychic'),
    'Claydol':('Ground', 'Psychic'),
    'Lileep':('Rock', 'Grass'),
    'Cradily':('Rock', 'Grass'),
    'Anorith':('Rock', 'Bug'),
    'Armaldo':('Rock', 'Bug'),
    'Feebas':'Water',
    'Milotic':'Water',
    'Castform':'Normal',
    'Kecleon':'Normal',
    'Shuppet':'Ghost',
    'Banette':'Ghost',
    'Duskull':'Ghost',
    'Dusclops':'Ghost',
    'Tropius':('Grass', 'Flying'),
    'Chimecho':'Psychic',
    'Absol':'Dark',
    'Wynaut':'Psychic',
    'Snorunt':'Ice',
    'Glalie':'Ice',
    'Spheal':('Ice', 'Water'),
    'Sealeo':('Ice', 'Water'),
    'Walrein':('Ice', 'Water'),
    'Clamperl':'Water',
    'Huntail':'Water',
    'Gorebyss':'Water',
    'Relicanth':('Water', 'Rock'),
    'Luvdisc':'Water',
    'Bagon':'Dragon',
    'Shelgon':'Dragon',
    'Salamence':('Dragon', 'Flying'),
    'Beldum':('Steel', 'Psychic'),
    'Metang':('Steel', 'Psychic'),
    'Metagross':('Steel', 'Psychic'),
    'Regirock':'Rock',
    'Regice':'Ice',
    'Registeel':'Steel',
    'Latias':('Dragon', 'Psychic'),
    'Latios':('Dragon', 'Psychic'),
    'Kyogre':'Water',
    'Groudon':'Ground',
    'Rayquaza':('Dragon', 'Flying'),
    'Jirachi':('Steel', 'Psychic'),
    'Deoxys':'Psychic',
    'Turtwig':'Grass',
    'Grotle':'Grass',
    'Torterra':('Grass', 'Ground'),
    'Chimchar':'Fire',
    'Monferno':('Fire', 'Fighting'),
    'Infernape':('Fire', 'Fighting'),
    'Piplup':'Water',
    'Prinplup':'Water',
    'Empoleon':('Water', 'Steel'),
    'Starly':('Normal', 'Flying'),
    'Staravia':('Normal', 'Flying'),
    'Staraptor':('Normal', 'Flying'),
    'Bidoof':'Normal',
    'Bibarel':('Normal', 'Water'),
    'Kricketot':'Bug',
    'Kricketune':'Bug',
    'Shinx':'Electric',
    'Luxio':'Electric',
    'Luxray':'Electric',
    'Budew':('Grass', 'Poison'),
    'Roserade':('Grass', 'Poison'),
    'Cranidos':'Rock',
    'Rampardos':'Rock',
    'Shieldon':('Rock', 'Steel'),
    'Bastiodon':('Rock', 'Steel'),
    'Burmy':'Bug',
    'Wormadam':('Bug', 'Grass'),
    'Mothim':('Bug', 'Flying'),
    'Combee':('Bug', 'Flying'),
    'Vespiquen':('Bug', 'Flying'),
    'Pachirisu':'Electric',
    'Buizel':'Water',
    'Floatzel':'Water',
    'Cherubi':'Grass',
    'Cherrim':'Grass',
    'Shellos':'Water',
    'Gastrodon':('Water', 'Ground'),
    'Ambipom':'Normal',
    'Drifloon':('Ghost', 'Flying'),
    'Drifblim':('Ghost', 'Flying'),
    'Buneary':'Normal',
    'Lopunny':'Normal',
    'Mismagius':'Ghost',
    'Honchkrow':('Dark', 'Flying'),
    'Glameow':'Normal',
    'Purugly':'Normal',
    'Chingling':'Psychic',
    'Stunky':('Poison', 'Dark'),
    'Skuntank':('Poison', 'Dark'),
    'Bronzor':('Steel', 'Psychic'),
    'Bronzong':('Steel', 'Psychic'),
    'Bonsly':'Rock',
    'Mime Jr.':'Psychic',
    'Happiny':'Normal',
    'Chatot':('Normal', 'Flying'),
    'Spiritomb':('Ghost', 'Dark'),
    'Gible':('Dragon', 'Ground'),
    'Gabite':('Dragon', 'Ground'),
    'Garchomp':('Dragon', 'Ground'),
    'Munchlax':'Normal',
    'Riolu':'Fighting',
    'Lucario':('Fighting', 'Steel'),
    'Hippopotas':'Ground',
    'Hippowdon':'Ground',
    'Skorupi':('Poison', 'Bug'),
    'Drapion':('Poison', 'Dark'),
    'Croagunk':('Poison', 'Fighting'),
    'Toxicroak':('Poison', 'Fighting'),
    'Carnivine':'Grass',
    'Finneon':'Water',
    'Lumineon':'Water',
    'Mantyke':('Water', 'Flying'),
    'Snover':('Grass', 'Ice'),
    'Abomasnow':('Grass', 'Ice'),
    'Weavile':('Dark', 'Ice'),
    'Magnezone':('Electric', 'Steel'),
    'Lickilicky':'Normal',
    'Rhyperior':('Ground', 'Rock'),
    'Tangrowth':'Grass',
    'Electivire':'Electric',
    'Magmortar':'Fire',
    'Togekiss':('Normal', 'Flying'),
    'Yanmega':('Bug', 'Flying'),
    'Leafeon':'Grass',
    'Glaceon':'Ice',
    'Gliscor':('Ground', 'Flying'),
    'Mamoswine':('Ice', 'Ground'),
    'Porygon-Z':'Normal',
    'Gallade':('Psychic', 'Fighting'),
    'Probopass':('Rock', 'Steel'),
    'Dusknoir':'Ghost',
    'Froslass':('Ice', 'Ghost'),
    'Rotom':('Electric', 'Ghost'),
    'Uxie':'Psychic',
    'Mesprit':'Psychic',
    'Azelf':'Psychic',
    'Dialga':('Steel', 'Dragon'),
    'Palkia':('Water', 'Dragon'),
    'Heatran':('Fire', 'Steel'),
    'Regigigas':'Normal',
    'Giratina':('Ghost', 'Dragon'),
    'Cresselia':'Psychic',
    'Phione':'Water',
    'Manaphy':'Water',
    'Darkrai':'Dark',
    'Shaymin':'Grass',
    'Arceus':'Normal',
    'Pokémon Egg':'???',
    'Manaphy Egg':'???',
}
moves_indexes = {
    1:{'name': 'Pound', 'type': 'Normal', 'category': 'Physical', 'pp': 35, 'power': '40', 'accuracy': '100%'},
    2:{'name': 'Karate Chop', 'type': 'Fighting', 'category': 'Physical', 'pp': 25, 'power': '50', 'accuracy': '100%'},
    3:{'name': 'Double Slap', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '15', 'accuracy': '85%'},
    4:{'name': 'Comet Punch', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '18', 'accuracy': '85%'},
    5:{'name': 'Mega Punch', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '80', 'accuracy': '85%'},
    6:{'name': 'Pay Day', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '40', 'accuracy': '100%'},
    7:{'name': 'Fire Punch', 'type': 'Fire', 'category': 'Physical', 'pp': 15, 'power': '75', 'accuracy': '100%'},
    8:{'name': 'Ice Punch', 'type': 'Ice', 'category': 'Physical', 'pp': 15, 'power': '75', 'accuracy': '100%'},
    9:{'name': 'Thunder Punch', 'type': 'Electric', 'category': 'Physical', 'pp': 15, 'power': '75', 'accuracy': '100%'},
    10:{'name': 'Scratch', 'type': 'Normal', 'category': 'Physical', 'pp': 35, 'power': '40', 'accuracy': '100%'},
    11:{'name': 'Vise Grip', 'type': 'Normal', 'category': 'Physical', 'pp': 30, 'power': '55', 'accuracy': '100%'},
    12:{'name': 'Guillotine', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '30%'},
    13:{'name': 'Razor Wind', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    14:{'name': 'Swords Dance', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    15:{'name': 'Cut', 'type': 'Normal', 'category': 'Physical', 'pp': 30, 'power': '50', 'accuracy': '95%'},
    16:{'name': 'Gust', 'type': 'Flying', 'category': 'Special', 'pp': 35, 'power': '40', 'accuracy': '100%'},
    17:{'name': 'Wing Attack', 'type': 'Flying', 'category': 'Physical', 'pp': 35, 'power': '60', 'accuracy': '100%'},
    18:{'name': 'Whirlwind', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    19:{'name': 'Fly', 'type': 'Flying', 'category': 'Physical', 'pp': 15, 'power': '90', 'accuracy': '95%'},
    20:{'name': 'Bind', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '15', 'accuracy': '85%'},
    21:{'name': 'Slam', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '80', 'accuracy': '75%'},
    22:{'name': 'Vine Whip', 'type': 'Grass', 'category': 'Physical', 'pp': 25, 'power': '45', 'accuracy': '100%'},
    23:{'name': 'Stomp', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    24:{'name': 'Double Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 30, 'power': '30', 'accuracy': '100%'},
    25:{'name': 'Mega Kick', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '120', 'accuracy': '75%'},
    26:{'name': 'Jump Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '95%'},
    27:{'name': 'Rolling Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 15, 'power': '60', 'accuracy': '85%'},
    28:{'name': 'Sand Attack', 'type': 'Ground', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    29:{'name': 'Headbutt', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '70', 'accuracy': '100%'},
    30:{'name': 'Horn Attack', 'type': 'Normal', 'category': 'Physical', 'pp': 25, 'power': '65', 'accuracy': '100%'},
    31:{'name': 'Fury Attack', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '15', 'accuracy': '85%'},
    32:{'name': 'Horn Drill', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '30%'},
    33:{'name': 'Tackle', 'type': 'Normal', 'category': 'Physical', 'pp': 35, 'power': '40', 'accuracy': '100%'},
    34:{'name': 'Body Slam', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '85', 'accuracy': '100%'},
    35:{'name': 'Wrap', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '15', 'accuracy': '90%'},
    36:{'name': 'Take Down', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '90', 'accuracy': '85%'},
    37:{'name': 'Thrash', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '120', 'accuracy': '100%'},
    38:{'name': 'Double-Edge', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '120', 'accuracy': '100%'},
    39:{'name': 'Tail Whip', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '100%'},
    40:{'name': 'Poison Sting', 'type': 'Poison', 'category': 'Physical', 'pp': 35, 'power': '15', 'accuracy': '100%'},
    41:{'name': 'Twineedle', 'type': 'Bug', 'category': 'Physical', 'pp': 20, 'power': '25', 'accuracy': '100%'},
    42:{'name': 'Pin Missile', 'type': 'Bug', 'category': 'Physical', 'pp': 20, 'power': '25', 'accuracy': '95%'},
    43:{'name': 'Leer', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '100%'},
    44:{'name': 'Bite', 'type': 'Dark', 'category': 'Physical', 'pp': 25, 'power': '60', 'accuracy': '100%'},
    45:{'name': 'Growl', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '100%'},
    46:{'name': 'Roar', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    47:{'name': 'Sing', 'type': 'Normal', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '55%'},
    48:{'name': 'Supersonic', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '55%'},
    49:{'name': 'Sonic Boom', 'type': 'Normal', 'category': 'Special', 'pp': 20, 'power': '20  damage', 'accuracy': '90%'},
    50:{'name': 'Disable', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    51:{'name': 'Acid', 'type': 'Poison', 'category': 'Special', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    52:{'name': 'Ember', 'type': 'Fire', 'category': 'Special', 'pp': 25, 'power': '40', 'accuracy': '100%'},
    53:{'name': 'Flamethrower', 'type': 'Fire', 'category': 'Special', 'pp': 15, 'power': '90', 'accuracy': '100%'},
    54:{'name': 'Mist', 'type': 'Ice', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    55:{'name': 'Water Gun', 'type': 'Water', 'category': 'Special', 'pp': 25, 'power': '40', 'accuracy': '100%'},
    56:{'name': 'Hydro Pump', 'type': 'Water', 'category': 'Special', 'pp': 5, 'power': '110', 'accuracy': '80%'},
    57:{'name': 'Surf', 'type': 'Water', 'category': 'Special', 'pp': 15, 'power': '90', 'accuracy': '100%'},
    58:{'name': 'Ice Beam', 'type': 'Ice', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    59:{'name': 'Blizzard', 'type': 'Ice', 'category': 'Special', 'pp': 5, 'power': '110', 'accuracy': '70%'},
    60:{'name': 'Psybeam', 'type': 'Psychic', 'category': 'Special', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    61:{'name': 'Bubble Beam', 'type': 'Water', 'category': 'Special', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    62:{'name': 'Aurora Beam', 'type': 'Ice', 'category': 'Special', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    63:{'name': 'Hyper Beam', 'type': 'Normal', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    64:{'name': 'Peck', 'type': 'Flying', 'category': 'Physical', 'pp': 35, 'power': '35', 'accuracy': '100%'},
    65:{'name': 'Drill Peck', 'type': 'Flying', 'category': 'Physical', 'pp': 20, 'power': '80', 'accuracy': '100%'},
    66:{'name': 'Submission', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '80', 'accuracy': '80%'},
    67:{'name': 'Low Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    68:{'name': 'Counter', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    69:{'name': 'Seismic Toss', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    70:{'name': 'Strength', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    71:{'name': 'Absorb', 'type': 'Grass', 'category': 'Special', 'pp': 25, 'power': '20', 'accuracy': '100%'},
    72:{'name': 'Mega Drain', 'type': 'Grass', 'category': 'Special', 'pp': 15, 'power': '40', 'accuracy': '100%'},
    73:{'name': 'Leech Seed', 'type': 'Grass', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '90%'},
    74:{'name': 'Growth', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    75:{'name': 'Razor Leaf', 'type': 'Grass', 'category': 'Physical', 'pp': 25, 'power': '55', 'accuracy': '95%'},
    76:{'name': 'Solar Beam', 'type': 'Grass', 'category': 'Special', 'pp': 10, 'power': '120', 'accuracy': '100%'},
    77:{'name': 'Poison Powder', 'type': 'Poison', 'category': 'Status', 'pp': 35, 'power': '—', 'accuracy': '75%'},
    78:{'name': 'Stun Spore', 'type': 'Grass', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '75%'},
    79:{'name': 'Sleep Powder', 'type': 'Grass', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '75%'},
    80:{'name': 'Petal Dance', 'type': 'Grass', 'category': 'Special', 'pp': 10, 'power': '120', 'accuracy': '100%'},
    81:{'name': 'String Shot', 'type': 'Bug', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '95%'},
    82:{'name': 'Dragon Rage', 'type': 'Dragon', 'category': 'Special', 'pp': 10, 'power': '40  damage', 'accuracy': '100%'},
    83:{'name': 'Fire Spin', 'type': 'Fire', 'category': 'Special', 'pp': 15, 'power': '35', 'accuracy': '85%'},
    84:{'name': 'Thunder Shock', 'type': 'Electric', 'category': 'Special', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    85:{'name': 'Thunderbolt', 'type': 'Electric', 'category': 'Special', 'pp': 15, 'power': '90', 'accuracy': '100%'},
    86:{'name': 'Thunder Wave', 'type': 'Electric', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '90%'},
    87:{'name': 'Thunder', 'type': 'Electric', 'category': 'Special', 'pp': 10, 'power': '110', 'accuracy': '70%'},
    88:{'name': 'Rock Throw', 'type': 'Rock', 'category': 'Physical', 'pp': 15, 'power': '50', 'accuracy': '90%'},
    89:{'name': 'Earthquake', 'type': 'Ground', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '100%'},
    90:{'name': 'Fissure', 'type': 'Ground', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '30%'},
    91:{'name': 'Dig', 'type': 'Ground', 'category': 'Physical', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    92:{'name': 'Toxic', 'type': 'Poison', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '90%'},
    93:{'name': 'Confusion', 'type': 'Psychic', 'category': 'Special', 'pp': 25, 'power': '50', 'accuracy': '100%'},
    94:{'name': 'Psychic', 'type': 'Psychic', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    95:{'name': 'Hypnosis', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '60%'},
    96:{'name': 'Meditate', 'type': 'Psychic', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    97:{'name': 'Agility', 'type': 'Psychic', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    98:{'name': 'Quick Attack', 'type': 'Normal', 'category': 'Physical', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    99:{'name': 'Rage', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '20', 'accuracy': '100%'},
    100:{'name': 'Teleport', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    101:{'name': 'Night Shade', 'type': 'Ghost', 'category': 'Special', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    102:{'name': 'Mimic', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    103:{'name': 'Screech', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '85%'},
    104:{'name': 'Double Team', 'type': 'Normal', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    105:{'name': 'Recover', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    106:{'name': 'Harden', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    107:{'name': 'Minimize', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    108:{'name': 'Smokescreen', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    109:{'name': 'Confuse Ray', 'type': 'Ghost', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    110:{'name': 'Withdraw', 'type': 'Water', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    111:{'name': 'Defense Curl', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    112:{'name': 'Barrier', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    113:{'name': 'Light Screen', 'type': 'Psychic', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    114:{'name': 'Haze', 'type': 'Ice', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    115:{'name': 'Reflect', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    116:{'name': 'Focus Energy', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    117:{'name': 'Bide', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '—', 'accuracy': '—'},
    118:{'name': 'Metronome', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    119:{'name': 'Mirror Move', 'type': 'Flying', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    120:{'name': 'Self-Destruct', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '200', 'accuracy': '100%'},
    121:{'name': 'Egg Bomb', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '75%'},
    122:{'name': 'Lick', 'type': 'Ghost', 'category': 'Physical', 'pp': 30, 'power': '30', 'accuracy': '100%'},
    123:{'name': 'Smog', 'type': 'Poison', 'category': 'Special', 'pp': 20, 'power': '30', 'accuracy': '70%'},
    124:{'name': 'Sludge', 'type': 'Poison', 'category': 'Special', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    125:{'name': 'Bone Club', 'type': 'Ground', 'category': 'Physical', 'pp': 20, 'power': '65', 'accuracy': '85%'},
    126:{'name': 'Fire Blast', 'type': 'Fire', 'category': 'Special', 'pp': 5, 'power': '110', 'accuracy': '85%'},
    127:{'name': 'Waterfall', 'type': 'Water', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    128:{'name': 'Clamp', 'type': 'Water', 'category': 'Physical', 'pp': 15, 'power': '35', 'accuracy': '85%'},
    129:{'name': 'Swift', 'type': 'Normal', 'category': 'Special', 'pp': 20, 'power': '60', 'accuracy': '—'},
    130:{'name': 'Skull Bash', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '130', 'accuracy': '100%'},
    131:{'name': 'Spike Cannon', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '20', 'accuracy': '100%'},
    132:{'name': 'Constrict', 'type': 'Normal', 'category': 'Physical', 'pp': 35, 'power': '10', 'accuracy': '100%'},
    133:{'name': 'Amnesia', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    134:{'name': 'Kinesis', 'type': 'Psychic', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '80%'},
    135:{'name': 'Soft-Boiled', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    136:{'name': 'High Jump Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '130', 'accuracy': '90%'},
    137:{'name': 'Glare', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '100%'},
    138:{'name': 'Dream Eater', 'type': 'Psychic', 'category': 'Special', 'pp': 15, 'power': '100', 'accuracy': '100%'},
    139:{'name': 'Poison Gas', 'type': 'Poison', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '90%'},
    140:{'name': 'Barrage', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '15', 'accuracy': '85%'},
    141:{'name': 'Leech Life', 'type': 'Bug', 'category': 'Physical', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    142:{'name': 'Lovely Kiss', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '75%'},
    143:{'name': 'Sky Attack', 'type': 'Flying', 'category': 'Physical', 'pp': 5, 'power': '140', 'accuracy': '90%'},
    144:{'name': 'Transform', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    145:{'name': 'Bubble', 'type': 'Water', 'category': 'Special', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    146:{'name': 'Dizzy Punch', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '70', 'accuracy': '100%'},
    147:{'name': 'Spore', 'type': 'Grass', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    148:{'name': 'Flash', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    149:{'name': 'Psywave', 'type': 'Psychic', 'category': 'Special', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    150:{'name': 'Splash', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    151:{'name': 'Acid Armor', 'type': 'Poison', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    152:{'name': 'Crabhammer', 'type': 'Water', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '90%'},
    153:{'name': 'Explosion', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '250', 'accuracy': '100%'},
    154:{'name': 'Fury Swipes', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '18', 'accuracy': '80%'},
    155:{'name': 'Bonemerang', 'type': 'Ground', 'category': 'Physical', 'pp': 10, 'power': '50', 'accuracy': '90%'},
    156:{'name': 'Rest', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    157:{'name': 'Rock Slide', 'type': 'Rock', 'category': 'Physical', 'pp': 10, 'power': '75', 'accuracy': '90%'},
    158:{'name': 'Hyper Fang', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '90%'},
    159:{'name': 'Sharpen', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    160:{'name': 'Conversion', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    161:{'name': 'Tri Attack', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    162:{'name': 'Super Fang', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '—', 'accuracy': '90%'},
    163:{'name': 'Slash', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    164:{'name': 'Substitute', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    165:{'name': 'Struggle', 'type': 'Normal', 'category': 'Physical', 'pp': 1, 'power': '50', 'accuracy': '—'},
    166:{'name': 'Sketch', 'type': 'Normal', 'category': 'Status', 'pp': 1, 'power': '—', 'accuracy': '—'},
    167:{'name': 'Triple Kick', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '10', 'accuracy': '90%'},
    168:{'name': 'Thief', 'type': 'Dark', 'category': 'Physical', 'pp': 25, 'power': '60', 'accuracy': '100%'},
    169:{'name': 'Spider Web', 'type': 'Bug', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    170:{'name': 'Mind Reader', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    171:{'name': 'Nightmare', 'type': 'Ghost', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    172:{'name': 'Flame Wheel', 'type': 'Fire', 'category': 'Physical', 'pp': 25, 'power': '60', 'accuracy': '100%'},
    173:{'name': 'Snore', 'type': 'Normal', 'category': 'Special', 'pp': 15, 'power': '50', 'accuracy': '100%'},
    174:{'name': 'Curse', 'type': 'Ghost', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    175:{'name': 'Flail', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    176:{'name': 'Conversion 2', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    177:{'name': 'Aeroblast', 'type': 'Flying', 'category': 'Special', 'pp': 5, 'power': '100', 'accuracy': '95%'},
    178:{'name': 'Cotton Spore', 'type': 'Grass', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '100%'},
    179:{'name': 'Reversal', 'type': 'Fighting', 'category': 'Physical', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    180:{'name': 'Spite', 'type': 'Ghost', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    181:{'name': 'Powder Snow', 'type': 'Ice', 'category': 'Special', 'pp': 25, 'power': '40', 'accuracy': '100%'},
    182:{'name': 'Protect', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    183:{'name': 'Mach Punch', 'type': 'Fighting', 'category': 'Physical', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    184:{'name': 'Scary Face', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    185:{'name': 'Feint Attack', 'type': 'Dark', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '—'},
    186:{'name': 'Sweet Kiss', 'type': 'Fairy', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '75%'},
    187:{'name': 'Belly Drum', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    188:{'name': 'Sludge Bomb', 'type': 'Poison', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    189:{'name': 'Mud-Slap', 'type': 'Ground', 'category': 'Special', 'pp': 10, 'power': '20', 'accuracy': '100%'},
    190:{'name': 'Octazooka', 'type': 'Water', 'category': 'Special', 'pp': 10, 'power': '65', 'accuracy': '85%'},
    191:{'name': 'Spikes', 'type': 'Ground', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    192:{'name': 'Zap Cannon', 'type': 'Electric', 'category': 'Special', 'pp': 5, 'power': '120', 'accuracy': '50%'},
    193:{'name': 'Foresight', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    194:{'name': 'Destiny Bond', 'type': 'Ghost', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    195:{'name': 'Perish Song', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    196:{'name': 'Icy Wind', 'type': 'Ice', 'category': 'Special', 'pp': 15, 'power': '55', 'accuracy': '95%'},
    197:{'name': 'Detect', 'type': 'Fighting', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    198:{'name': 'Bone Rush', 'type': 'Ground', 'category': 'Physical', 'pp': 10, 'power': '25', 'accuracy': '90%'},
    199:{'name': 'Lock-On', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    200:{'name': 'Outrage', 'type': 'Dragon', 'category': 'Physical', 'pp': 10, 'power': '120', 'accuracy': '100%'},
    201:{'name': 'Sandstorm', 'type': 'Rock', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    202:{'name': 'Giga Drain', 'type': 'Grass', 'category': 'Special', 'pp': 10, 'power': '75', 'accuracy': '100%'},
    203:{'name': 'Endure', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    204:{'name': 'Charm', 'type': 'Fairy', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    205:{'name': 'Rollout', 'type': 'Rock', 'category': 'Physical', 'pp': 20, 'power': '30', 'accuracy': '90%'},
    206:{'name': 'False Swipe', 'type': 'Normal', 'category': 'Physical', 'pp': 40, 'power': '40', 'accuracy': '100%'},
    207:{'name': 'Swagger', 'type': 'Normal', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '85%'},
    208:{'name': 'Milk Drink', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    209:{'name': 'Spark', 'type': 'Electric', 'category': 'Physical', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    210:{'name': 'Fury Cutter', 'type': 'Bug', 'category': 'Physical', 'pp': 20, 'power': '40', 'accuracy': '95%'},
    211:{'name': 'Steel Wing', 'type': 'Steel', 'category': 'Physical', 'pp': 25, 'power': '70', 'accuracy': '90%'},
    212:{'name': 'Mean Look', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    213:{'name': 'Attract', 'type': 'Normal', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    214:{'name': 'Sleep Talk', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    215:{'name': 'Heal Bell', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    216:{'name': 'Return', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    217:{'name': 'Present', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '—', 'accuracy': '90%'},
    218:{'name': 'Frustration', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    219:{'name': 'Safeguard', 'type': 'Normal', 'category': 'Status', 'pp': 25, 'power': '—', 'accuracy': '—'},
    220:{'name': 'Pain Split', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    221:{'name': 'Sacred Fire', 'type': 'Fire', 'category': 'Physical', 'pp': 5, 'power': '100', 'accuracy': '95%'},
    222:{'name': 'Magnitude', 'type': 'Ground', 'category': 'Physical', 'pp': 30, 'power': '—', 'accuracy': '100%'},
    223:{'name': 'Dynamic Punch', 'type': 'Fighting', 'category': 'Physical', 'pp': 5, 'power': '100', 'accuracy': '50%'},
    224:{'name': 'Megahorn', 'type': 'Bug', 'category': 'Physical', 'pp': 10, 'power': '120', 'accuracy': '85%'},
    225:{'name': 'Dragon Breath', 'type': 'Dragon', 'category': 'Special', 'pp': 20, 'power': '60', 'accuracy': '100%'},
    226:{'name': 'Baton Pass', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    227:{'name': 'Encore', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    228:{'name': 'Pursuit', 'type': 'Dark', 'category': 'Physical', 'pp': 20, 'power': '40', 'accuracy': '100%'},
    229:{'name': 'Rapid Spin', 'type': 'Normal', 'category': 'Physical', 'pp': 40, 'power': '50', 'accuracy': '100%'},
    230:{'name': 'Sweet Scent', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    231:{'name': 'Iron Tail', 'type': 'Steel', 'category': 'Physical', 'pp': 15, 'power': '100', 'accuracy': '75%'},
    232:{'name': 'Metal Claw', 'type': 'Steel', 'category': 'Physical', 'pp': 35, 'power': '50', 'accuracy': '95%'},
    233:{'name': 'Vital Throw', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '70', 'accuracy': '—'},
    234:{'name': 'Morning Sun', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    235:{'name': 'Synthesis', 'type': 'Grass', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    236:{'name': 'Moonlight', 'type': 'Fairy', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    237:{'name': 'Hidden Power', 'type': 'Normal', 'category': 'Special', 'pp': 15, 'power': '60', 'accuracy': '100%'},
    238:{'name': 'Cross Chop', 'type': 'Fighting', 'category': 'Physical', 'pp': 5, 'power': '100', 'accuracy': '80%'},
    239:{'name': 'Twister', 'type': 'Dragon', 'category': 'Special', 'pp': 20, 'power': '40', 'accuracy': '100%'},
    240:{'name': 'Rain Dance', 'type': 'Water', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    241:{'name': 'Sunny Day', 'type': 'Fire', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    242:{'name': 'Crunch', 'type': 'Dark', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    243:{'name': 'Mirror Coat', 'type': 'Psychic', 'category': 'Special', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    244:{'name': 'Psych Up', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    245:{'name': 'Extreme Speed', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '80', 'accuracy': '100%'},
    246:{'name': 'Ancient Power', 'type': 'Rock', 'category': 'Special', 'pp': 5, 'power': '60', 'accuracy': '100%'},
    247:{'name': 'Shadow Ball', 'type': 'Ghost', 'category': 'Special', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    248:{'name': 'Future Sight', 'type': 'Psychic', 'category': 'Special', 'pp': 10, 'power': '120', 'accuracy': '100%'},
    249:{'name': 'Rock Smash', 'type': 'Fighting', 'category': 'Physical', 'pp': 15, 'power': '40', 'accuracy': '100%'},
    250:{'name': 'Whirlpool', 'type': 'Water', 'category': 'Special', 'pp': 15, 'power': '35', 'accuracy': '85%'},
    251:{'name': 'Beat Up', 'type': 'Dark', 'category': 'Physical', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    252:{'name': 'Fake Out', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '40', 'accuracy': '100%'},
    253:{'name': 'Uproar', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    254:{'name': 'Stockpile', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    255:{'name': 'Spit Up', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    256:{'name': 'Swallow', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    257:{'name': 'Heat Wave', 'type': 'Fire', 'category': 'Special', 'pp': 10, 'power': '95', 'accuracy': '90%'},
    258:{'name': 'Hail', 'type': 'Ice', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    259:{'name': 'Torment', 'type': 'Dark', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    260:{'name': 'Flatter', 'type': 'Dark', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    261:{'name': 'Will-O-Wisp', 'type': 'Fire', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '85%'},
    262:{'name': 'Memento', 'type': 'Dark', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    263:{'name': 'Facade', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    264:{'name': 'Focus Punch', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '150', 'accuracy': '100%'},
    265:{'name': 'Smelling Salts', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '70', 'accuracy': '100%'},
    266:{'name': 'Follow Me', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    267:{'name': 'Nature Power', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    268:{'name': 'Charge', 'type': 'Electric', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    269:{'name': 'Taunt', 'type': 'Dark', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    270:{'name': 'Helping Hand', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    271:{'name': 'Trick', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    272:{'name': 'Role Play', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    273:{'name': 'Wish', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    274:{'name': 'Assist', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    275:{'name': 'Ingrain', 'type': 'Grass', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    276:{'name': 'Superpower', 'type': 'Fighting', 'category': 'Physical', 'pp': 5, 'power': '120', 'accuracy': '100%'},
    277:{'name': 'Magic Coat', 'type': 'Psychic', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    278:{'name': 'Recycle', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    279:{'name': 'Revenge', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '60', 'accuracy': '100%'},
    280:{'name': 'Brick Break', 'type': 'Fighting', 'category': 'Physical', 'pp': 15, 'power': '75', 'accuracy': '100%'},
    281:{'name': 'Yawn', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    282:{'name': 'Knock Off', 'type': 'Dark', 'category': 'Physical', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    283:{'name': 'Endeavor', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    284:{'name': 'Eruption', 'type': 'Fire', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '100%'},
    285:{'name': 'Skill Swap', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    286:{'name': 'Imprison', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    287:{'name': 'Refresh', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    288:{'name': 'Grudge', 'type': 'Ghost', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    289:{'name': 'Snatch', 'type': 'Dark', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    290:{'name': 'Secret Power', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    291:{'name': 'Dive', 'type': 'Water', 'category': 'Physical', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    292:{'name': 'Arm Thrust', 'type': 'Fighting', 'category': 'Physical', 'pp': 20, 'power': '15', 'accuracy': '100%'},
    293:{'name': 'Camouflage', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    294:{'name': 'Tail Glow', 'type': 'Bug', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    295:{'name': 'Luster Purge', 'type': 'Psychic', 'category': 'Special', 'pp': 5, 'power': '70', 'accuracy': '100%'},
    296:{'name': 'Mist Ball', 'type': 'Psychic', 'category': 'Special', 'pp': 5, 'power': '70', 'accuracy': '100%'},
    297:{'name': 'Feather Dance', 'type': 'Flying', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    298:{'name': 'Teeter Dance', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    299:{'name': 'Blaze Kick', 'type': 'Fire', 'category': 'Physical', 'pp': 10, 'power': '85', 'accuracy': '90%'},
    300:{'name': 'Mud Sport', 'type': 'Ground', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    301:{'name': 'Ice Ball', 'type': 'Ice', 'category': 'Physical', 'pp': 20, 'power': '30', 'accuracy': '90%'},
    302:{'name': 'Needle Arm', 'type': 'Grass', 'category': 'Physical', 'pp': 15, 'power': '60', 'accuracy': '100%'},
    303:{'name': 'Slack Off', 'type': 'Normal', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    304:{'name': 'Hyper Voice', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    305:{'name': 'Poison Fang', 'type': 'Poison', 'category': 'Physical', 'pp': 15, 'power': '50', 'accuracy': '100%'},
    306:{'name': 'Crush Claw', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '75', 'accuracy': '95%'},
    307:{'name': 'Blast Burn', 'type': 'Fire', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    308:{'name': 'Hydro Cannon', 'type': 'Water', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    309:{'name': 'Meteor Mash', 'type': 'Steel', 'category': 'Physical', 'pp': 10, 'power': '90', 'accuracy': '90%'},
    310:{'name': 'Astonish', 'type': 'Ghost', 'category': 'Physical', 'pp': 15, 'power': '30', 'accuracy': '100%'},
    311:{'name': 'Weather Ball', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '50', 'accuracy': '100%'},
    312:{'name': 'Aromatherapy', 'type': 'Grass', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    313:{'name': 'Fake Tears', 'type': 'Dark', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    314:{'name': 'Air Cutter', 'type': 'Flying', 'category': 'Special', 'pp': 25, 'power': '60', 'accuracy': '95%'},
    315:{'name': 'Overheat', 'type': 'Fire', 'category': 'Special', 'pp': 5, 'power': '130', 'accuracy': '90%'},
    316:{'name': 'Odor Sleuth', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    317:{'name': 'Rock Tomb', 'type': 'Rock', 'category': 'Physical', 'pp': 15, 'power': '60', 'accuracy': '95%'},
    318:{'name': 'Silver Wind', 'type': 'Bug', 'category': 'Special', 'pp': 5, 'power': '60', 'accuracy': '100%'},
    319:{'name': 'Metal Sound', 'type': 'Steel', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '85%'},
    320:{'name': 'Grass Whistle', 'type': 'Grass', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '55%'},
    321:{'name': 'Tickle', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    322:{'name': 'Cosmic Power', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    323:{'name': 'Water Spout', 'type': 'Water', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '100%'},
    324:{'name': 'Signal Beam', 'type': 'Bug', 'category': 'Special', 'pp': 15, 'power': '75', 'accuracy': '100%'},
    325:{'name': 'Shadow Punch', 'type': 'Ghost', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '—'},
    326:{'name': 'Extrasensory', 'type': 'Psychic', 'category': 'Special', 'pp': 20, 'power': '80', 'accuracy': '100%'},
    327:{'name': 'Sky Uppercut', 'type': 'Fighting', 'category': 'Physical', 'pp': 15, 'power': '85', 'accuracy': '90%'},
    328:{'name': 'Sand Tomb', 'type': 'Ground', 'category': 'Physical', 'pp': 15, 'power': '35', 'accuracy': '85%'},
    329:{'name': 'Sheer Cold', 'type': 'Ice', 'category': 'Special', 'pp': 5, 'power': '—', 'accuracy': '30%'},
    330:{'name': 'Muddy Water', 'type': 'Water', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '85%'},
    331:{'name': 'Bullet Seed', 'type': 'Grass', 'category': 'Physical', 'pp': 30, 'power': '25', 'accuracy': '100%'},
    332:{'name': 'Aerial Ace', 'type': 'Flying', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '—'},
    333:{'name': 'Icicle Spear', 'type': 'Ice', 'category': 'Physical', 'pp': 30, 'power': '25', 'accuracy': '100%'},
    334:{'name': 'Iron Defense', 'type': 'Steel', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    335:{'name': 'Block', 'type': 'Normal', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    336:{'name': 'Howl', 'type': 'Normal', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    337:{'name': 'Dragon Claw', 'type': 'Dragon', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    338:{'name': 'Frenzy Plant', 'type': 'Grass', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    339:{'name': 'Bulk Up', 'type': 'Fighting', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    340:{'name': 'Bounce', 'type': 'Flying', 'category': 'Physical', 'pp': 5, 'power': '85', 'accuracy': '85%'},
    341:{'name': 'Mud Shot', 'type': 'Ground', 'category': 'Special', 'pp': 15, 'power': '55', 'accuracy': '95%'},
    342:{'name': 'Poison Tail', 'type': 'Poison', 'category': 'Physical', 'pp': 25, 'power': '50', 'accuracy': '100%'},
    343:{'name': 'Covet', 'type': 'Normal', 'category': 'Physical', 'pp': 25, 'power': '60', 'accuracy': '100%'},
    344:{'name': 'Volt Tackle', 'type': 'Electric', 'category': 'Physical', 'pp': 15, 'power': '120', 'accuracy': '100%'},
    345:{'name': 'Magical Leaf', 'type': 'Grass', 'category': 'Special', 'pp': 20, 'power': '60', 'accuracy': '—'},
    346:{'name': 'Water Sport', 'type': 'Water', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    347:{'name': 'Calm Mind', 'type': 'Psychic', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    348:{'name': 'Leaf Blade', 'type': 'Grass', 'category': 'Physical', 'pp': 15, 'power': '90', 'accuracy': '100%'},
    349:{'name': 'Dragon Dance', 'type': 'Dragon', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    350:{'name': 'Rock Blast', 'type': 'Rock', 'category': 'Physical', 'pp': 10, 'power': '25', 'accuracy': '90%'},
    351:{'name': 'Shock Wave', 'type': 'Electric', 'category': 'Special', 'pp': 20, 'power': '60', 'accuracy': '—'},
    352:{'name': 'Water Pulse', 'type': 'Water', 'category': 'Special', 'pp': 20, 'power': '60', 'accuracy': '100%'},
    353:{'name': 'Doom Desire', 'type': 'Steel', 'category': 'Special', 'pp': 5, 'power': '140', 'accuracy': '100%'},
    354:{'name': 'Psycho Boost', 'type': 'Psychic', 'category': 'Special', 'pp': 5, 'power': '140', 'accuracy': '90%'},
    355:{'name': 'Roost', 'type': 'Flying', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    356:{'name': 'Gravity', 'type': 'Psychic', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    357:{'name': 'Miracle Eye', 'type': 'Psychic', 'category': 'Status', 'pp': 40, 'power': '—', 'accuracy': '—'},
    358:{'name': 'Wake-Up Slap', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '70', 'accuracy': '100%'},
    359:{'name': 'Hammer Arm', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '90%'},
    360:{'name': 'Gyro Ball', 'type': 'Steel', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    361:{'name': 'Healing Wish', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    362:{'name': 'Brine', 'type': 'Water', 'category': 'Special', 'pp': 10, 'power': '65', 'accuracy': '100%'},
    363:{'name': 'Natural Gift', 'type': 'Normal', 'category': 'Physical', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    364:{'name': 'Feint', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '30', 'accuracy': '100%'},
    365:{'name': 'Pluck', 'type': 'Flying', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '100%'},
    366:{'name': 'Tailwind', 'type': 'Flying', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    367:{'name': 'Acupressure', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    368:{'name': 'Metal Burst', 'type': 'Steel', 'category': 'Physical', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    369:{'name': 'U-turn', 'type': 'Bug', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    370:{'name': 'Close Combat', 'type': 'Fighting', 'category': 'Physical', 'pp': 5, 'power': '120', 'accuracy': '100%'},
    371:{'name': 'Payback', 'type': 'Dark', 'category': 'Physical', 'pp': 10, 'power': '50', 'accuracy': '100%'},
    372:{'name': 'Assurance', 'type': 'Dark', 'category': 'Physical', 'pp': 10, 'power': '60', 'accuracy': '100%'},
    373:{'name': 'Embargo', 'type': 'Dark', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    374:{'name': 'Fling', 'type': 'Dark', 'category': 'Physical', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    375:{'name': 'Psycho Shift', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    376:{'name': 'Trump Card', 'type': 'Normal', 'category': 'Special', 'pp': 5, 'power': '—', 'accuracy': '—'},
    377:{'name': 'Heal Block', 'type': 'Psychic', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '100%'},
    378:{'name': 'Wring Out', 'type': 'Normal', 'category': 'Special', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    379:{'name': 'Power Trick', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    380:{'name': 'Gastro Acid', 'type': 'Poison', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    381:{'name': 'Lucky Chant', 'type': 'Normal', 'category': 'Status', 'pp': 30, 'power': '—', 'accuracy': '—'},
    382:{'name': 'Me First', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    383:{'name': 'Copycat', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    384:{'name': 'Power Swap', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    385:{'name': 'Guard Swap', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    386:{'name': 'Punishment', 'type': 'Dark', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    387:{'name': 'Last Resort', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '140', 'accuracy': '100%'},
    388:{'name': 'Worry Seed', 'type': 'Grass', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    389:{'name': 'Sucker Punch', 'type': 'Dark', 'category': 'Physical', 'pp': 5, 'power': '70', 'accuracy': '100%'},
    390:{'name': 'Toxic Spikes', 'type': 'Poison', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    391:{'name': 'Heart Swap', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    392:{'name': 'Aqua Ring', 'type': 'Water', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    393:{'name': 'Magnet Rise', 'type': 'Electric', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    394:{'name': 'Flare Blitz', 'type': 'Fire', 'category': 'Physical', 'pp': 15, 'power': '120', 'accuracy': '100%'},
    395:{'name': 'Force Palm', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '60', 'accuracy': '100%'},
    396:{'name': 'Aura Sphere', 'type': 'Fighting', 'category': 'Special', 'pp': 20, 'power': '80', 'accuracy': '—'},
    397:{'name': 'Rock Polish', 'type': 'Rock', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    398:{'name': 'Poison Jab', 'type': 'Poison', 'category': 'Physical', 'pp': 20, 'power': '80', 'accuracy': '100%'},
    399:{'name': 'Dark Pulse', 'type': 'Dark', 'category': 'Special', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    400:{'name': 'Night Slash', 'type': 'Dark', 'category': 'Physical', 'pp': 15, 'power': '70', 'accuracy': '100%'},
    401:{'name': 'Aqua Tail', 'type': 'Water', 'category': 'Physical', 'pp': 10, 'power': '90', 'accuracy': '90%'},
    402:{'name': 'Seed Bomb', 'type': 'Grass', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    403:{'name': 'Air Slash', 'type': 'Flying', 'category': 'Special', 'pp': 15, 'power': '75', 'accuracy': '95%'},
    404:{'name': 'X-Scissor', 'type': 'Bug', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    405:{'name': 'Bug Buzz', 'type': 'Bug', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    406:{'name': 'Dragon Pulse', 'type': 'Dragon', 'category': 'Special', 'pp': 10, 'power': '85', 'accuracy': '100%'},
    407:{'name': 'Dragon Rush', 'type': 'Dragon', 'category': 'Physical', 'pp': 10, 'power': '100', 'accuracy': '75%'},
    408:{'name': 'Power Gem', 'type': 'Rock', 'category': 'Special', 'pp': 20, 'power': '80', 'accuracy': '100%'},
    409:{'name': 'Drain Punch', 'type': 'Fighting', 'category': 'Physical', 'pp': 10, 'power': '75', 'accuracy': '100%'},
    410:{'name': 'Vacuum Wave', 'type': 'Fighting', 'category': 'Special', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    411:{'name': 'Focus Blast', 'type': 'Fighting', 'category': 'Special', 'pp': 5, 'power': '120', 'accuracy': '70%'},
    412:{'name': 'Energy Ball', 'type': 'Grass', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    413:{'name': 'Brave Bird', 'type': 'Flying', 'category': 'Physical', 'pp': 15, 'power': '120', 'accuracy': '100%'},
    414:{'name': 'Earth Power', 'type': 'Ground', 'category': 'Special', 'pp': 10, 'power': '90', 'accuracy': '100%'},
    415:{'name': 'Switcheroo', 'type': 'Dark', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '100%'},
    416:{'name': 'Giga Impact', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    417:{'name': 'Nasty Plot', 'type': 'Dark', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    418:{'name': 'Bullet Punch', 'type': 'Steel', 'category': 'Physical', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    419:{'name': 'Avalanche', 'type': 'Ice', 'category': 'Physical', 'pp': 10, 'power': '60', 'accuracy': '100%'},
    420:{'name': 'Ice Shard', 'type': 'Ice', 'category': 'Physical', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    421:{'name': 'Shadow Claw', 'type': 'Ghost', 'category': 'Physical', 'pp': 15, 'power': '70', 'accuracy': '100%'},
    422:{'name': 'Thunder Fang', 'type': 'Electric', 'category': 'Physical', 'pp': 15, 'power': '65', 'accuracy': '95%'},
    423:{'name': 'Ice Fang', 'type': 'Ice', 'category': 'Physical', 'pp': 15, 'power': '65', 'accuracy': '95%'},
    424:{'name': 'Fire Fang', 'type': 'Fire', 'category': 'Physical', 'pp': 15, 'power': '65', 'accuracy': '95%'},
    425:{'name': 'Shadow Sneak', 'type': 'Ghost', 'category': 'Physical', 'pp': 30, 'power': '40', 'accuracy': '100%'},
    426:{'name': 'Mud Bomb', 'type': 'Ground', 'category': 'Special', 'pp': 10, 'power': '65', 'accuracy': '85%'},
    427:{'name': 'Psycho Cut', 'type': 'Psychic', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    428:{'name': 'Zen Headbutt', 'type': 'Psychic', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '90%'},
    429:{'name': 'Mirror Shot', 'type': 'Steel', 'category': 'Special', 'pp': 10, 'power': '65', 'accuracy': '85%'},
    430:{'name': 'Flash Cannon', 'type': 'Steel', 'category': 'Special', 'pp': 10, 'power': '80', 'accuracy': '100%'},
    431:{'name': 'Rock Climb', 'type': 'Normal', 'category': 'Physical', 'pp': 20, 'power': '90', 'accuracy': '85%'},
    432:{'name': 'Defog', 'type': 'Flying', 'category': 'Status', 'pp': 15, 'power': '—', 'accuracy': '—'},
    433:{'name': 'Trick Room', 'type': 'Psychic', 'category': 'Status', 'pp': 5, 'power': '—', 'accuracy': '—'},
    434:{'name': 'Draco Meteor', 'type': 'Dragon', 'category': 'Special', 'pp': 5, 'power': '130', 'accuracy': '90%'},
    435:{'name': 'Discharge', 'type': 'Electric', 'category': 'Special', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    436:{'name': 'Lava Plume', 'type': 'Fire', 'category': 'Special', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    437:{'name': 'Leaf Storm', 'type': 'Grass', 'category': 'Special', 'pp': 5, 'power': '130', 'accuracy': '90%'},
    438:{'name': 'Power Whip', 'type': 'Grass', 'category': 'Physical', 'pp': 10, 'power': '120', 'accuracy': '85%'},
    439:{'name': 'Rock Wrecker', 'type': 'Rock', 'category': 'Physical', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    440:{'name': 'Cross Poison', 'type': 'Poison', 'category': 'Physical', 'pp': 20, 'power': '70', 'accuracy': '100%'},
    441:{'name': 'Gunk Shot', 'type': 'Poison', 'category': 'Physical', 'pp': 5, 'power': '120', 'accuracy': '80%'},
    442:{'name': 'Iron Head', 'type': 'Steel', 'category': 'Physical', 'pp': 15, 'power': '80', 'accuracy': '100%'},
    443:{'name': 'Magnet Bomb', 'type': 'Steel', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '—'},
    444:{'name': 'Stone Edge', 'type': 'Rock', 'category': 'Physical', 'pp': 5, 'power': '100', 'accuracy': '80%'},
    445:{'name': 'Captivate', 'type': 'Normal', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    446:{'name': 'Stealth Rock', 'type': 'Rock', 'category': 'Status', 'pp': 20, 'power': '—', 'accuracy': '—'},
    447:{'name': 'Grass Knot', 'type': 'Grass', 'category': 'Special', 'pp': 20, 'power': '—', 'accuracy': '100%'},
    448:{'name': 'Chatter', 'type': 'Flying', 'category': 'Special', 'pp': 20, 'power': '65', 'accuracy': '100%'},
    449:{'name': 'Judgment', 'type': 'Normal', 'category': 'Special', 'pp': 10, 'power': '100', 'accuracy': '100%'},
    450:{'name': 'Bug Bite', 'type': 'Bug', 'category': 'Physical', 'pp': 20, 'power': '60', 'accuracy': '100%'},
    451:{'name': 'Charge Beam', 'type': 'Electric', 'category': 'Special', 'pp': 10, 'power': '50', 'accuracy': '90%'},
    452:{'name': 'Wood Hammer', 'type': 'Grass', 'category': 'Physical', 'pp': 15, 'power': '120', 'accuracy': '100%'},
    453:{'name': 'Aqua Jet', 'type': 'Water', 'category': 'Physical', 'pp': 20, 'power': '40', 'accuracy': '100%'},
    454:{'name': 'Attack Order', 'type': 'Bug', 'category': 'Physical', 'pp': 15, 'power': '90', 'accuracy': '100%'},
    455:{'name': 'Defend Order', 'type': 'Bug', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    456:{'name': 'Heal Order', 'type': 'Bug', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    457:{'name': 'Head Smash', 'type': 'Rock', 'category': 'Physical', 'pp': 5, 'power': '150', 'accuracy': '80%'},
    458:{'name': 'Double Hit', 'type': 'Normal', 'category': 'Physical', 'pp': 10, 'power': '35', 'accuracy': '90%'},
    459:{'name': 'Roar of Time', 'type': 'Dragon', 'category': 'Special', 'pp': 5, 'power': '150', 'accuracy': '90%'},
    460:{'name': 'Spacial Rend', 'type': 'Dragon', 'category': 'Special', 'pp': 5, 'power': '100', 'accuracy': '95%'},
    461:{'name': 'Lunar Dance', 'type': 'Psychic', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '—'},
    462:{'name': 'Crush Grip', 'type': 'Normal', 'category': 'Physical', 'pp': 5, 'power': '—', 'accuracy': '100%'},
    463:{'name': 'Magma Storm', 'type': 'Fire', 'category': 'Special', 'pp': 5, 'power': '100', 'accuracy': '75%'},
    464:{'name': 'Dark Void', 'type': 'Dark', 'category': 'Status', 'pp': 10, 'power': '—', 'accuracy': '50%'},
    465:{'name': 'Seed Flare', 'type': 'Grass', 'category': 'Special', 'pp': 5, 'power': '120', 'accuracy': '85%'},
    466:{'name': 'Ominous Wind', 'type': 'Ghost', 'category': 'Special', 'pp': 5, 'power': '60', 'accuracy': '100%'},
    467:{'name': 'Shadow Force', 'type': 'Ghost', 'category': 'Physical', 'pp': 5, 'power': '120', 'accuracy': '100%'},
}
